/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandsignup;

import java.util.Scanner;

/**
 *
 * @author Laptop
 */
 class CashierPayment extends javax.swing.JFrame {

    /**
     * Creates new form CashierPayment
     */
    public CashierPayment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Payments");

        jLabel2.setText("Refunds");

        jButton1.setText("Cash");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Card");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Vouchers");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("E-Wallet");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Refunds");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Gift Voucher");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Discounts");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton5)
                        .addGap(51, 51, 51)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(28, 28, 28)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
import java.util.Scanner;

 class CashInputExample {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        System.out.println("Welcome to the Cash Input Program!");

        // Get the item price from the user
        System.out.print("Enter the item price: $");
        double itemPrice = scanner.nextDouble();

        // Get the amount paid by the user
        System.out.print("Enter the amount paid: $");
        double amountPaid = scanner.nextDouble();

        // Calculate the change
        double change = amountPaid - itemPrice;

        // Display the change
        if (change >= 0) {
            System.out.println("Change: $" + change);
            calculateChangeDenominations(change);
        } else {
            System.out.println("Insufficient payment. Please provide enough funds.");
        }

        scanner.close();
    }

    private static void calculateChangeDenominations(double change) {
        int[] denominations = {100, 50, 20, 10, 5, 1, 25, 10, 5, 1}; // Assuming dollars and cents
        String[] names = {"$100", "$50", "$20", "$10", "$5", "$1", "quarters", "dimes", "nickels", "pennies"};

        System.out.println("Change breakdown:");

        for (int i = 0; i < denominations.length; i++) {
            int count = (int) (change / denominations[i]);
            if (count > 0) {
                System.out.println(names[i] + ": " + count);
                change -= count * denominations[i];
            }
        }
    }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        import javax.swing.JOptionPane;

public class YourCashTransactionForm extends javax.swing.JFrame {

    public YourCashTransactionForm() {
        initComponents();
    }

    private void initComponents() {
        // Initialization of UI components goes here
        // ...

        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("Process Voucher Transaction");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        // Add jButton3 to your layout

        pack();
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // Prompt the user to enter voucher details
        try {
            String voucherCode = JOptionPane.showInputDialog("Enter voucher code:");
            if (voucherCode != null) {

                // Now you have the voucher code, you can use it as needed
                // For example, display it in a message dialog
                JOptionPane.showMessageDialog(this, "Entered Voucher Code: " + voucherCode);

                // Alternatively, you can perform other actions based on the voucher code
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter valid values.");
        }
    }

    public static void main(String args[]) {
        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YourCashTransactionForm().setVisible(true);
            }
        });
    }

    // Variables declaration
    private javax.swing.JButton jButton3;
    // Other UI components go here
    // ...
}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       public class YourRefundTransactionForm extends javax.swing.JFrame {

    public YourRefundTransactionForm() {
        initComponents();
    }

    private void initComponents() {
        // Initialization of UI components goes here
        // ...

        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton5.setText("Process Refund");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        // Add jButton5 to your layout

        pack();
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        // Prompt the user to enter refund details
        try {
            String refundDetails = JOptionPane.showInputDialog("Enter refund details:");
            if (refundDetails != null) {
                // Process the refund transaction
                boolean refundSuccessful = processRefund(refundDetails);

                if (refundSuccessful) {
                    JOptionPane.showMessageDialog(this, "Refund processed successfully.");
                } else {
                    JOptionPane.showMessageDialog(this, "Refund processing failed.");
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter valid values.");
        }
    }

    private boolean processRefund(String refundDetails) {
        // Implement your refund logic here
        // For example, interact with your backend or data source to update refund status
        // You may need to return a boolean indicating the success or failure of the refund process

        // Placeholder implementation
        return true;
    }

    public static void main(String args[]) {
        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YourRefundTransactionForm().setVisible(true);
            }
        });
    }

    // Variables declaration
    private javax.swing.JButton jButton5;
    // Other UI components go here
    // ...
}


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.util.Random;

public class DiscountGeneratorForm extends javax.swing.JFrame {

    public DiscountGeneratorForm() {
        initComponents();
    }

    private void initComponents() {
        // Initialization of UI components goes here
        // ...

        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton7.setText("Generate Discount");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        // Add jButton7 to your layout

        pack();
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        // Generate and display a random discount
        double discount = generateRandomDiscount();
        JOptionPane.showMessageDialog(this, "Generated Discount: " + discount + "%");
    }

    private double generateRandomDiscount() {
        // Define the range of possible discounts
        double minDiscount = 5.0;
        double maxDiscount = 20.0;

        // Create a random object
        Random random = new Random();

        // Generate a random discount within the specified range
        return minDiscount + (maxDiscount - minDiscount) * random.nextDouble();
    }

    public static void main(String args[]) {
        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiscountGeneratorForm().setVisible(true);
            }
        });
    }

    // Variables declaration
    private javax.swing.JButton jButton7;
    // Other UI components go here
    // ...
}

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
import javax.swing.JOptionPane;

public class YourCashTransactionForm extends javax.swing.JFrame {

    public YourCashTransactionForm() {
        initComponents();
    }

    private void initComponents() {
        // Initialization of UI components goes here
        // ...

        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Process Card Transaction");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        // Add jButton2 to your layout

        pack();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // Prompt the user to enter card details
        try {
            String cardNumber = JOptionPane.showInputDialog("Enter card number:");
            if (cardNumber != null) {
                String expirationDate = JOptionPane.showInputDialog("Enter expiration date (MM/YY):");
                String cvv = JOptionPane.showInputDialog("Enter CVV:");

                // Now you have the card details, you can use them as needed
                // For example, display them in a message dialog
                String cardDetails = "Card Number: " + cardNumber + "\nExpiration Date: " + expirationDate + "\nCVV: " + cvv;
                JOptionPane.showMessageDialog(this, "Entered Card Details:\n" + cardDetails);

                // Alternatively, you can perform other actions based on the card details
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter valid numeric values.");
        }
    }

    public static void main(String args[]) {
        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YourCashTransactionForm().setVisible(true);
            }
        });
    }

    // Variables declaration
    private javax.swing.JButton jButton2;
    // Other UI components go here
    // ...
}
// commentS
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.util.Random;

public class GiftVoucherGeneratorForm extends javax.swing.JFrame {

    public GiftVoucherGeneratorForm() {
        initComponents();
    }

    private void initComponents() {
        // Initialization of UI components goes here
        // ...

        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton6.setText("Generate Gift Voucher");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        // Add jButton6 to your layout

        pack();
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        // Generate and display a random gift voucher code
        String voucherCode = generateRandomVoucherCode();
        JOptionPane.showMessageDialog(this, "Generated Gift Voucher Code: " + voucherCode);
    }

    private String generateRandomVoucherCode() {
        // Define the characters allowed in the voucher code
        String allowedCharacters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

        // Define the length of the voucher code
        int voucherCodeLength = 10;

        // Create a random object
        Random random = new Random();

        // Generate the voucher code
        StringBuilder voucherCodeBuilder = new StringBuilder();
        for (int i = 0; i < voucherCodeLength; i++) {
            int randomIndex = random.nextInt(allowedCharacters.length());
            char randomChar = allowedCharacters.charAt(randomIndex);
            voucherCodeBuilder.append(randomChar);
        }

        return voucherCodeBuilder.toString();
    }

    public static void main(String args[]) {
        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiftVoucherGeneratorForm().setVisible(true);
            }
        });
    }

    // Variables declaration
    private javax.swing.JButton jButton6;
    // Other UI components go here
    // ...
}

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
