/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package posinventory;

/**
 *
 * @author User
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
public class addInventory extends javax.swing.JFrame {

    /**
     * Creates new form addInventory
     */
    public addInventory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addProduct = new javax.swing.JLabel();
        prodName = new javax.swing.JLabel();
        prodInputName = new javax.swing.JTextField();
        prodBarcode = new javax.swing.JLabel();
        prodInputBarcode = new javax.swing.JTextField();
        prodCategory = new javax.swing.JLabel();
        prodInputCategory = new javax.swing.JTextField();
        prodPrice = new javax.swing.JLabel();
        prodInputPrice = new javax.swing.JTextField();
        priceStockLevel = new javax.swing.JLabel();
        prodInputStockLevel = new javax.swing.JTextField();
        prodReorderLevel = new javax.swing.JLabel();
        prodInputReorderLevel = new javax.swing.JTextField();
        goButton = new javax.swing.JButton();
        backButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addProduct.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        addProduct.setText("ADD PRODUCT");

        prodName.setText("PRODUCT NAME");

        prodBarcode.setText("BARCODE");

        prodCategory.setText("CATEGORY");

        prodPrice.setText("PRICE");

        priceStockLevel.setText("STOCK LEVEL");

        prodReorderLevel.setText("REORDER LEVEL");

        goButton.setText("GO");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        backButton2.setText("BACK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodName)
                            .addComponent(prodBarcode)
                            .addComponent(prodCategory)
                            .addComponent(prodPrice)
                            .addComponent(priceStockLevel)
                            .addComponent(prodReorderLevel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prodInputName)
                            .addComponent(prodInputBarcode)
                            .addComponent(prodInputPrice)
                            .addComponent(prodInputStockLevel)
                            .addComponent(prodInputReorderLevel)
                            .addComponent(prodInputCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addProduct)))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(goButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButton2)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addProduct)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodName)
                    .addComponent(prodInputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodBarcode)
                    .addComponent(prodInputBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prodCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prodPrice)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceStockLevel)
                            .addComponent(prodInputStockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prodReorderLevel)
                            .addComponent(prodInputReorderLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(prodInputCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prodInputPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goButton)
                    .addComponent(backButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private Connection connection; // Define connection at class level
                                       
    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
    // Some parts of your code...


    try {
        // Load the MariaDB JDBC driver
        Class.forName("org.mariadb.jdbc.Driver");

        // Establish the connection
        String url = "jdbc:mariadb://localhost:3306/teamspiritpos";
        String username = "root";
        String password = "";

        connection = DriverManager.getConnection(url, username, password);

        String sql = "INSERT INTO products (product_name, barcode, category, price, stock_level, reorder_level) VALUES (?, ?, ?, ?, ?, ?)";

        PreparedStatement statement = connection.prepareStatement(sql);
        statement.setString(1, prodInputName.getText()); // Replace with the appropriate input fields
        statement.setString(2, prodInputBarcode.getText());
        statement.setString(3, prodInputCategory.getText());
        statement.setDouble(4, Double.parseDouble(prodInputPrice.getText()));
        statement.setInt(5, Integer.parseInt(prodInputStockLevel.getText()));
        statement.setInt(6, Integer.parseInt(prodInputReorderLevel.getText()));

        int rowsAffected = statement.executeUpdate();
        if (rowsAffected > 0) {
            System.out.println("Input successful!");
        } else {
            System.out.println("Input failed. Please try again.");
        }
        
        // Close the statement and connection
        statement.close();
        connection.close();
    } catch (ClassNotFoundException | SQLException ex) {
        // Handle any errors
        ex.printStackTrace();
    }
   
    
    }//GEN-LAST:event_goButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addInventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addProduct;
    private javax.swing.JButton backButton2;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel priceStockLevel;
    private javax.swing.JLabel prodBarcode;
    private javax.swing.JLabel prodCategory;
    private javax.swing.JTextField prodInputBarcode;
    private javax.swing.JTextField prodInputCategory;
    private javax.swing.JTextField prodInputName;
    private javax.swing.JTextField prodInputPrice;
    private javax.swing.JTextField prodInputReorderLevel;
    private javax.swing.JTextField prodInputStockLevel;
    private javax.swing.JLabel prodName;
    private javax.swing.JLabel prodPrice;
    private javax.swing.JLabel prodReorderLevel;
    // End of variables declaration//GEN-END:variables
}
